VexCL: vex::profiler< Clock, Avg > Class Template Reference
vex::profiler< Clock, Avg > Class Template Reference
Class for gathering and printing OpenCL and Host profiling info.
#include <profiler.hpp>
Public Member Functions
profiler (const std::vector< cl::CommandQueue > &queue=std::vector< cl::CommandQueue >(), const std::string &name="Profile")
Constructor.
void tic_cpu (const std::string &name)
Starts a CPU timer.
void tic_cl (const std::string &name)
Enqueues a marker into each of the provided queues.
double toc (const std::string &)
Returns time since last tic.
void print (std::ostream &out)
Outputs profile to the provided stream.
Detailed Description
template<class Clock = boost::chrono::high_resolution_clock, AvgKind Avg = AvgMedian>
class vex::profiler< Clock, Avg >
Class for gathering and printing OpenCL and Host profiling info.
Parameters
Clock class that provides interface compatible with either boost::chrono or std::chrono clocks.
Avg Kind of averaging used. AvgMedian is more stable, but may have high overhead when profiling is made in a loop.
Constructor & Destructor Documentation
template<class Clock = boost::chrono::high_resolution_clock, AvgKind Avg = AvgMedian> vex::profiler< Clock, Avg >::profiler (const std::vector< cl::CommandQueue > & queue = std::vector<cl::CommandQueue>(), const std::string & name = "Profile") inline
Constructor.
Parameters
queue vector of command queues.
name Optional name to be used when profiling info is printed.
Member Function Documentation
template<class Clock = boost::chrono::high_resolution_clock, AvgKind Avg = AvgMedian> void vex::profiler< Clock, Avg >::tic_cl (const std::string & name) inline
Enqueues a marker into each of the provided queues.
Also pushes named interval to the top of the profiler hierarchy.
Parameters
name name of the measured interval.
Referenced by vex::device_spmv_perf(), and vex::device_vector_perf().
template<class Clock = boost::chrono::high_resolution_clock, AvgKind Avg = AvgMedian> void vex::profiler< Clock, Avg >::tic_cpu (const std::string & name) inline
Starts a CPU timer.
Also pushes named interval to the top of the profiler hierarchy.
Parameters
name name of the measured interval.
template<class Clock = boost::chrono::high_resolution_clock, AvgKind Avg = AvgMedian> double vex::profiler< Clock, Avg >::toc (const std::string &) inline
Returns time since last tic.
Also removes interval from the top of the profiler hierarchy.
Referenced by vex::device_spmv_perf(), and vex::device_vector_perf().
The documentation for this class was generated from the following file:
vexcl/profiler.hpp