VexCL: vex::stencil< T > Class Template Reference
vex::stencil< T > Class Template Reference
Stencil.
#include <stencil.hpp>
Inherits stencil_base< T >.
Public Types
typedef T value_type
Public Member Functions
stencil (const std::vector< cl::CommandQueue > &queue, const std::vector< T > &st, unsigned center)
Costructor.
template<class Iterator >
stencil (const std::vector< cl::CommandQueue > &queue, Iterator begin, Iterator end, unsigned center)
Costructor.
stencil (const std::vector< cl::CommandQueue > &queue, std::initializer_list< T > list, unsigned center)
Costructor.
void convolve (const vex::vector< T > &x, vex::vector< T > &y, T alpha=0, T beta=1) const
Convolve stencil with a vector.
Detailed Description
template<typename T>
class vex::stencil< T >
Stencil.
Should be used for stencil convolutions with vex::vectors as in
void convolve(
         const vex::stencil<double> &s,
         const vex::vector<double>  &x,
         vex::vector<double> &y)
{
    y = x * s;
}
Stencil should be small enough to fit into local memory of all compute devices it resides on.
Constructor & Destructor Documentation
template<typename T> vex::stencil< T >::stencil (const std::vector< cl::CommandQueue > & queue, const std::vector< T > & st, unsigned center) inline
Costructor.
Parameters
queue vector of queues. Each queue represents one compute device.
st vector holding stencil values.
center center of the stencil.
template<typename T> template<class Iterator > vex::stencil< T >::stencil (const std::vector< cl::CommandQueue > & queue, Iterator begin, Iterator end, unsigned center) inline
Costructor.
Parameters
queue vector of queues. Each queue represents one compute device.
begin iterator to begin of sequence holding stencil data.
end iterator to end of sequence holding stencil data.
center center of the stencil.
template<typename T> vex::stencil< T >::stencil (const std::vector< cl::CommandQueue > & queue, std::initializer_list< T > list, unsigned center) inline
Costructor.
Parameters
queue vector of queues. Each queue represents one compute device.
list intializer list holding stencil values.
center center of the stencil.
Member Function Documentation
template<typename T > void vex::stencil< T >::convolve (const vex::vector< T > & x, vex::vector< T > & y, T alpha = 0, T beta = 1) const
Convolve stencil with a vector.
y = alpha * y + beta * conv(x);
Parameters
x input vector.
y output vector.
alpha Scaling coefficient in front of y.
beta Scaling coefficient in front of convolution.
References vex::alignup(), vex::is_cpu(), vex::num_workgroups(), vex::vector< T >::part_size(), vex::qctx(), and vex::qdev().
The documentation for this class was generated from the following file:
vexcl/stencil.hpp